### PR TITLE
Bugfix swift get object

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Bug Fix: swift driver async utility had wrong arguments for get_object()
Bug Fix: Cassandra Driver no longer had full test coverage under some configurations

### CODE REVIEW

**Comment by TheSriram** [comment]
:+1:

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/291/

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/292/

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/294/

**Comment by jc7998** [comment]
:+1:

**Comment by racklanta** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/295/

**Pull request merged**
