### PR TITLE
feat: disallow assigning of bad blocks to a file

### PR DESCRIPTION
**Pull request by TheSriram**

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
:+1:

**Comment by racklanta** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/275/

**Comment by raxyu** [comment]
:+1:

**Comment by TheSriram** [comment]
DO NOT MERGE YET: adding tests to explicit test associated scenarios.

**Comment by TheSriram** [comment]
@painterjd @BenjamenMeyer @raxyu Could you guys take a look again? Its been updated.

**Comment by racklanta** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/276/

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/277/

**Comment by TheSriram** [comment]
The travis build failed, due to some transient error, I have restarted it.

**Comment by racklanta** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/280/

**Comment by BenjamenMeyer** [comment]
:+1:

**Comment by raxyu** [comment]
:+1:

**Pull request merged**
