### PR TITLE
fix: swift driver correctly recognizes missing blocks from storage as 40...

### PR DESCRIPTION
**Pull request by TheSriram**
...4s

- disk storage driver also makes sures that if given a marker (good in
  format) but not exisiting, supplies the elements after it in a
  sorted order

### CODE REVIEW

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/262/

**Comment by jc7998** [comment]
:+1 
Verified functionality of the PR with #254 , the corresponding API Test

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/265/

**Comment by BenjamenMeyer** [comment]
:+1: since @jc7998 has the API test in too per https://github.com/rackerlabs/deuce/pull/253#issuecomment-70855133

**Pull request merged**
