### PR TITLE
Enhancement: Only the deuce user should be able to read/write to a vault

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
- Only the Deuce User should be able to list/read/write to a vault
- The group the Deuce User is under should be able to read/read a vault
- No one else should be able to see into the vault

### CODE REVIEW

**Comment by painterjd** [comment]
If you're going to do that, why set the execute bit on block files? Shouldn't those be mode 640? That would give you read/write for user, read for group.

**Comment by BenjamenMeyer** [comment]
@painterjd done, and a little more maintainable now too ;-)

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/224/

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/225/

**Comment by racklanta** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/244/

**Comment by painterjd** [comment]
:+1:

**Comment by TheSriram** [comment]
:+1:

**Pull request merged**
