### PR TITLE
fix: swift get_container

### PR DESCRIPTION
**Pull request by TheSriram**
- Must decode content, not the response

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
:+1:

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/226/

**Comment by racklanta** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/237/

**Comment by racklanta** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/240/

**Comment by painterjd** [comment]
lol. :+1:

**Pull request merged**
