### PR TITLE
Bugfix multi vault file block assignment

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Bug Fix: Assigning the same block to different files in different vaults makes on file fail in the assignment

- Enhancement: Added test to cover the scenario to the Sqlite Driver Tests
- Bug Fix: Corrected the Sqlite Query that produced the error
- Oddity: Removing the Sqlite change seems to make all three backends fail the provided test; adding it makes them all pass. Not sure why.

Note: This was PR #250

### CODE REVIEW

**Comment by racklanta** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://ci.cldbckp.com/job/deuce-pullrequest/267/

**Comment by BenjamenMeyer** [comment]
@lichray  this fixes the issue you reported

**Comment by lichray** [comment]
LGTM

**Comment by TheSriram** [comment]
:+1:

**Pull request merged**
